version: "3.8"

services:
  back:
    container_name: backend-container
    build:
      context: ./server/highfourm
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://database-container:3307/highfourm?useSSL=false&amp;serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=1111
      - TZ=Asia/Seoul
    ports:
      - "9999:8080"
    depends_on:
      - database
  fornt:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  database:
    container_name: database-container
    build:
      context: ./server/highfourm
      dockerfile: Dockerfile-db
    hostname: docker-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: highfourm
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111